services:
  whoami:
    image: traefik/whoami:v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.spaceduck.cloud`)
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=letsencryptprod
    restart: unless-stopped
    networks:
      - whoami
      - traefik
networks:
  traefik:
    name: traefik_default
    external: true
  whoami:

