services:
  whoami:
    image: traefik/whoami:v1.12.0@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.spaceduck.cloud`)
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=letsencryptprod
    restart: always
    networks:
      - whoami
      - traefik
networks:
  traefik:
    name: traefik_default
    external: true
  whoami:

