services:
  homeassistant:
    labels:
      - traefik.http.routers.homeassistant.rule=Host(`home.spaceduck.cloud`)
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=letsencryptprod
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_data:/config
    networks:
      - home
      - traefik
    environment:
      - TZ=America/Halifax

  zigbee2mqtt:
    labels:
      - traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.spaceduck.cloud`)
      - traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080
      - traefik.http.routers.zigbee2mqtt.tls=true
      - traefik.http.routers.zigbee2mqtt.tls.certresolver=letsencryptprod
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - zigbee2mqtt_data:/app/data
    environment:
      - TZ=America/Halifax
      - ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_FRONTEND_URL=https://zigbee2mqtt.spaceduck.cloud
    networks:
      - home
      - traefik

volumes:
  homeassistant_data:
  zigbee2mqtt_data:
networks:
  traefik:
    name: traefik_default
    external: true
  home:
