services:
  homeassistant:
    labels:
      - traefik.http.routers.homeassistant.rule=Host(`home.spaceduck.cloud`)
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=letsencryptprod
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_data:/config
    networks:
      - home
      - traefik
    environment:
      - TZ=America/Halifax

  zigbee2mqtt:
    labels:
      - traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.spaceduck.cloud`)
      - traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080
      - traefik.http.routers.zigbee2mqtt.tls=true
      - traefik.http.routers.zigbee2mqtt.tls.certresolver=letsencryptprod
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - zigbee2mqtt_data:/app/data
    environment:
      - TZ=America/Halifax
      - ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_FRONTEND_URL=https://zigbee2mqtt.spaceduck.cloud
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=tcp://192.168.1.90:6638
      - ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE=115200
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=ezsp
      - ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER=20
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mosquitto:1883
    networks:
      - home
      - traefik
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - mosquitto_data:/mosquitto/data
    networks:
      - home
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf

volumes:
  homeassistant_data:
  zigbee2mqtt_data:
  mosquitto_data:
  mosquitto_config:
networks:
  traefik:
    name: traefik_default
    external: true
  home:

configs:
  mosquitto_config:
    content: |
      persistence true
      persistence_location /mosquitto/data/
      log_dest file /mosquitto/log/mosquitto.log
      listener 1883
      allow_anonymous true
