services:
  homeassistant:
    labels:
      - traefik.http.routers.homeassistant.rule=Host(`home.spaceduck.cloud`)
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=letsencryptprod
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_data:/config
    ports:
      - 8123:8123
    networks:
      - home
      - traefik
  filebrowser:
    labels:
      - traefik.http.routers.filebrowser.rule=Host(`home-files.spaceduck.cloud`)
      - traefik.http.services.filebrowser.loadbalancer.server.port=80
      - traefik.http.routers.filebrowser.tls=true
      - traefik.http.routers.filebrowser.tls.certresolver=letsencryptprod
    image: filebrowser/filebrowser
    volumes:
      - homeassistant_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
    networks:
      - traefik
volumes:
  homeassistant_data:
  filebrowser_database:
  filebrowser_config:
networks:
  traefik:
    name: traefik_default
    external: true
  home:
